apiVersion: app.cp4mcm.ibm.com/v1alpha1
kind: DeployerSet
metadata:
  name: default-mydeployer
  labels:
    app.kubernetes.io/instance: hybridapplication-operator
    app.kubernetes.io/managed-by: hybridapplication-operator
    app.kubernetes.io/name: hybridapplication
spec:
  deployers:
  - key: cloudform/builtin
    spec:
      type: cloudform
