apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployer-operator
  template:
    metadata:
      labels:
        name: deployer-operator
    spec:
      serviceAccountName: deployer-operator
      containers:
        - name: deployer-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - deployer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "deployer-operator"
          livenessProbe:
            exec:
              command:
              - ls
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
              - ls
            initialDelaySeconds: 15
            periodSeconds: 15
