apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: deployer-operator
rules:
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - deployer-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - app.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
