kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-operator
  labels:
    app.kubernetes.io/instance: hybridapplication-operator
    app.kubernetes.io/managed-by: hybridapplication-operator
    app.kubernetes.io/name: hybridapplication
subjects:
- kind: ServiceAccount
  name: deployer-operator
roleRef:
  kind: ClusterRole
  name: deployer-operator
  apiGroup: rbac.authorization.k8s.io
