apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-operator
  labels:
    app.kubernetes.io/instance: hybridapplication-operator
    app.kubernetes.io/managed-by: hybridapplication-operator
    app.kubernetes.io/name: hybridapplication
